export const productSearchResults = {
  status: "OK",
  request_id: "64dea9dc-a3bb-4665-814d-216203ce8b32",
  data: {
    total_products: 91,
    country: "US",
    products: [
      {
        asin: "B0BWLHGVC9",
        product_title:
          "Womens Short Sleeve Dress Casual Crewneck Dresses Loose Comfy Swing Sundress with Pockets",
        product_price: "$35.99",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 109,
        product_url: "https://www.amazon.com/dp/B0BWLHGVC9",
        product_photo:
          "https://m.media-amazon.com/images/I/61NbLYLJalL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$35.99",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B082ZTBNZ3",
        product_title: "Women's Sleeveless Woven Shift Dress",
        product_price: "$23.70",
        product_original_price: "$24.90",
        currency: "USD",
        product_star_rating: "4.2",
        product_num_ratings: 1709,
        product_url: "https://www.amazon.com/dp/B082ZTBNZ3",
        product_photo:
          "https://m.media-amazon.com/images/I/71Ugann9HzL._AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$23.70",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B082ZSXXF5",
        product_title: "Women's Sleeveless Woven Shirt Dress",
        product_price: "$27.50",
        product_original_price: "$28.90",
        currency: "USD",
        product_star_rating: "4.1",
        product_num_ratings: 1795,
        product_url: "https://www.amazon.com/dp/B082ZSXXF5",
        product_photo:
          "https://m.media-amazon.com/images/I/71MgC-YUitL._AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$27.50",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BZ3LLBHC",
        product_title:
          "Women Casual Long Sleeve Dresses, Stretchy Sun Dress Sleeveless Slip Tank Sundress Ruffle Wrap Spaghetti Strap Tie Knot",
        product_price: "$5.35",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BZ3LLBHC",
        product_photo:
          "https://m.media-amazon.com/images/I/71X5HgSc5gL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$5.35",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B07DJVLHNR",
        product_title:
          "Women's Jersey Relaxed-Fit Muscle-Sleeve Swing Dress (Previously Daily Ritual)",
        product_price: "$20.90",
        product_original_price: "$21.90",
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 2670,
        product_url: "https://www.amazon.com/dp/B07DJVLHNR",
        product_photo:
          "https://m.media-amazon.com/images/I/61bsXXe7JLS._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$20.90",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B09R17MYG9",
        product_title:
          "Women's Relaxed Fit Lightweight Georgette Split Neck Flutter Sleeve Shift Dress",
        product_price: "$41.80",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.2",
        product_num_ratings: 68,
        product_url: "https://www.amazon.com/dp/B09R17MYG9",
        product_photo:
          "https://m.media-amazon.com/images/I/71QdJf0uN9L._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$41.80",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B07YGP1CN1",
        product_title: "Women's Standard Short-Sleeve V-Neck Swing Dress",
        product_price: "$19.92",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 4628,
        product_url: "https://www.amazon.com/dp/B07YGP1CN1",
        product_photo:
          "https://m.media-amazon.com/images/I/61ruFkZQnIL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$19.92",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B08JH3RLKP",
        product_title: "Women's Waisted Maxi Dress (Available in Plus Size)",
        product_price: "$25.90",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 7487,
        product_url: "https://www.amazon.com/dp/B08JH3RLKP",
        product_photo:
          "https://m.media-amazon.com/images/I/91GWYOTONLL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$25.90",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B07JP75S63",
        product_title: "Women's Tank Swing Dress (Available in Plus Size)",
        product_price: "$21.52",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.4",
        product_num_ratings: 7981,
        product_url: "https://www.amazon.com/dp/B07JP75S63",
        product_photo:
          "https://m.media-amazon.com/images/I/61MBfTs2jhL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$21.52",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B07YGL1G4F",
        product_title: "Women's Cap-Sleeve Faux-Wrap Dress",
        product_price: "$23.70",
        product_original_price: "$24.90",
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 4545,
        product_url: "https://www.amazon.com/dp/B07YGL1G4F",
        product_photo:
          "https://m.media-amazon.com/images/I/71V4QC+VS8L._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$23.70",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BRX6C5XY",
        product_title:
          "Women's V Neck Front Knotted Sleeveless Tank Dress Summer Solid Casual A Line Dress",
        product_price: "$25.99",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 15,
        product_url: "https://www.amazon.com/dp/B0BRX6C5XY",
        product_photo:
          "https://m.media-amazon.com/images/I/61Qfqmo7bsL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$25.99",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B09TT2CD7M",
        product_title:
          "Women's Summer Cute V-Neck Ruffle Bell Sleeve Flowy Shift Dress Tunic Dress Mini Dresses",
        product_price: "$33.99",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.1",
        product_num_ratings: 255,
        product_url: "https://www.amazon.com/dp/B09TT2CD7M",
        product_photo:
          "https://m.media-amazon.com/images/I/51J11j4B8bL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$33.99",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B07PW81FTT",
        product_title:
          "Women Summer Tunic Dress V Neck Casual Loose Flowy Swing Shift Dresses",
        product_price: "$32.98",
        product_original_price: "$52.99",
        currency: "USD",
        product_star_rating: "3.9",
        product_num_ratings: 60213,
        product_url: "https://www.amazon.com/dp/B07PW81FTT",
        product_photo:
          "https://m.media-amazon.com/images/I/71JFaKnNJhL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$32.98",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B09QX32HYN",
        product_title:
          "Women's V Neck Sleeveless Button Down Dress Casual Summer Elastic Waist A-Line Swing Tank Mini Dresses",
        product_price: "$25.49",
        product_original_price: "$31.99",
        currency: "USD",
        product_star_rating: "4.2",
        product_num_ratings: 1217,
        product_url: "https://www.amazon.com/dp/B09QX32HYN",
        product_photo:
          "https://m.media-amazon.com/images/I/61d6MnfV4LL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$25.49",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B071JMFW93",
        product_title:
          "Women's Jersey Standard-Fit Sleeveless V-Neck Midi Dress (Previously Daily Ritual)",
        product_price: "$19.92",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 5284,
        product_url: "https://www.amazon.com/dp/B071JMFW93",
        product_photo:
          "https://m.media-amazon.com/images/I/61D-LNqcdyL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$19.92",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B09R2F252K",
        product_title:
          "Women's Gathered Short Sleeve Crew Neck Shift Dress (Available in Plus Size)",
        product_price: "$31.30",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.4",
        product_num_ratings: 77,
        product_url: "https://www.amazon.com/dp/B09R2F252K",
        product_photo:
          "https://m.media-amazon.com/images/I/71eHFZ3QObL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$31.30",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B07JNS4LNK",
        product_title:
          "Women's Tank Waisted Maxi Dress (Available in Plus Size)",
        product_price: "$25.60",
        product_original_price: "$26.90",
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 5541,
        product_url: "https://www.amazon.com/dp/B07JNS4LNK",
        product_photo:
          "https://m.media-amazon.com/images/I/71-78Bgq4QL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$25.60",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B082ZTCRN5",
        product_title: "Women's Short-Sleeve Midi Button Front Tie Dress",
        product_price: "$31.30",
        product_original_price: "$32.90",
        currency: "USD",
        product_star_rating: "4",
        product_num_ratings: 653,
        product_url: "https://www.amazon.com/dp/B082ZTCRN5",
        product_photo:
          "https://m.media-amazon.com/images/I/71mKii89hZL._AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$31.30",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BR5D5YYG",
        product_title:
          "Womens Casual Summer Dresses Sleeveless Tiered Halter Sun Dress Tie Back",
        product_price: "$32.99",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.6",
        product_num_ratings: 14,
        product_url: "https://www.amazon.com/dp/B0BR5D5YYG",
        product_photo:
          "https://m.media-amazon.com/images/I/51ShkJFs8LL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$32.99",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B00J0OUQMY",
        product_title:
          "Etc Solid Color Comfort Fit Short-Sleeve Terry Cotton Summer Dress with Side Pockets and Elastic Scooped Neckline",
        product_price: "$33.98",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.1",
        product_num_ratings: 57,
        product_url: "https://www.amazon.com/dp/B00J0OUQMY",
        product_photo:
          "https://m.media-amazon.com/images/I/617v7+txDuL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$33.98",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B07SQPZ8YP",
        product_title:
          "Women Summer Sleeveless Damask Print T-Shirt Dress with Pockets(S-3XL)",
        product_price: "$27.99",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 7003,
        product_url: "https://www.amazon.com/dp/B07SQPZ8YP",
        product_photo:
          "https://m.media-amazon.com/images/I/71islNn+-lL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$27.99",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B08YWVDFLW",
        product_title:
          "Women Summer Casual T Shirt Dress for 2022 Short Sleeve Loose Beach Sundress with Pockets",
        product_price: "$23.99",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 105,
        product_url: "https://www.amazon.com/dp/B08YWVDFLW",
        product_photo:
          "https://m.media-amazon.com/images/I/91kCC3VrVWL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$23.99",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B09R2FQBND",
        product_title:
          "Women's Sleeveless Crossover Twist Neck Faux Wrap Dress",
        product_price: "$23.92",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 50,
        product_url: "https://www.amazon.com/dp/B09R2FQBND",
        product_photo:
          "https://m.media-amazon.com/images/I/61p-LgZj0-L._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$23.92",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B07JNS8M4R",
        product_title:
          "Women's Short-Sleeve Scoop Neck Swing Dress (Available in Plus Size)",
        product_price: "$19.00",
        product_original_price: "$19.90",
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 10277,
        product_url: "https://www.amazon.com/dp/B07JNS8M4R",
        product_photo:
          "https://m.media-amazon.com/images/I/61cdAu5ytYL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$19.00",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B09HSVX6LQ",
        product_title:
          "Women's Sleeveless Elastic Waist Summer Maxi Dress (Available in Plus Size)",
        product_price: "$33.00",
        product_original_price: "$35.80",
        currency: "USD",
        product_star_rating: "4",
        product_num_ratings: 407,
        product_url: "https://www.amazon.com/dp/B09HSVX6LQ",
        product_photo:
          "https://m.media-amazon.com/images/I/71ZJK+scBeL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$33.00",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BXY2LFSZ",
        product_title:
          "Oversized Linen Shirt Dress for Women Button Down Collared Shirt Dress Linen Shift Dress Dressy Casual Summer Dress",
        product_price: "$10.19",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BXY2LFSZ",
        product_photo:
          "https://m.media-amazon.com/images/I/61bV05Z7TiL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$10.19",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B082K9QPCQ",
        product_title:
          "2023 Women's Summer Dress Sleeveless Ruffle Sleeve Round Neck Mini Dress Solid Loose Short Flowy Pleated Dress",
        product_price: "$32.29",
        product_original_price: "$37.99",
        currency: "USD",
        product_star_rating: "3.9",
        product_num_ratings: 13424,
        product_url: "https://www.amazon.com/dp/B082K9QPCQ",
        product_photo:
          "https://m.media-amazon.com/images/I/71YwUFDO-KL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$32.29",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BVZLKR68",
        product_title:
          "Women's Satin Lace Strap Mini Dress Square Neck Flowy A-Line Ruffle Swing Short Dresses",
        product_price: "$32.99",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "3.7",
        product_num_ratings: 12,
        product_url: "https://www.amazon.com/dp/B0BVZLKR68",
        product_photo:
          "https://m.media-amazon.com/images/I/61jn7hdfTBL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$32.99",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BS6TZCC2",
        product_title:
          "Women Summer Casual V Neck T Shirt Dresses Beach Cover up Plain Tank Dress",
        product_price: "$30.99",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 10872,
        product_url: "https://www.amazon.com/dp/B0BS6TZCC2",
        product_photo:
          "https://m.media-amazon.com/images/I/61ETeLZG7xL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$30.99",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B07JP84111",
        product_title: "Women's Tank Maxi Dress",
        product_price: "$22.32",
        product_original_price: "$27.90",
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 5641,
        product_url: "https://www.amazon.com/dp/B07JP84111",
        product_photo:
          "https://m.media-amazon.com/images/I/612Kbk1VRUL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$22.32",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B07JNS4LXM",
        product_title: "Women's Surplice Dress (Available in Plus Size)",
        product_price: "$19.92",
        product_original_price: "$24.90",
        currency: "USD",
        product_star_rating: "4.4",
        product_num_ratings: 6740,
        product_url: "https://www.amazon.com/dp/B07JNS4LXM",
        product_photo:
          "https://m.media-amazon.com/images/I/71RekvU1V1S._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$19.92",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B07JMVMT9T",
        product_title: "Women's Short-Sleeve Maxi Dress",
        product_price: "$25.60",
        product_original_price: "$26.90",
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 5284,
        product_url: "https://www.amazon.com/dp/B07JMVMT9T",
        product_photo:
          "https://m.media-amazon.com/images/I/61GVCF3Nc0S._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$25.60",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BXY4KXGS",
        product_title:
          "Linen Shirt Dresses for Women Plus Size Flowy Beach Vacation Dress Sexy V Neck Sundress Irregular Hem Summer Dress",
        product_price: "$17.27",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BXY4KXGS",
        product_photo:
          "https://m.media-amazon.com/images/I/51AJeYMfxbL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$17.27",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BZ51DBQ5",
        product_title:
          "Women Boho Summer Dress, V Neck Sleeveless Front Lace Up Backless Dress Bohemian Fashion Skater A Line Ruffle Hem Womens",
        product_price: "$5.49",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BZ51DBQ5",
        product_photo:
          "https://m.media-amazon.com/images/I/619nhxVRq5L._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$5.49",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B07JN9J7LR",
        product_title:
          "Women's Short-Sleeve Waisted Maxi Dress (Available in Plus Size)",
        product_price: "$23.92",
        product_original_price: "$29.90",
        currency: "USD",
        product_star_rating: "4.4",
        product_num_ratings: 6337,
        product_url: "https://www.amazon.com/dp/B07JN9J7LR",
        product_photo:
          "https://m.media-amazon.com/images/I/71VxyADuAJL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$23.92",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B09HCVBZJM",
        product_title:
          "Women's Short Sleeve Elastic Waist Cotton Jersey Minidress",
        product_price: "$19.12",
        product_original_price: "$24.90",
        currency: "USD",
        product_star_rating: "4",
        product_num_ratings: 178,
        product_url: "https://www.amazon.com/dp/B09HCVBZJM",
        product_photo:
          "https://m.media-amazon.com/images/I/61nz3VIG3eL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$19.12",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B09TNHSMLT",
        product_title:
          "2023 Women's Summer Mini Dress Casual V Neck Floral Embroidered Ruffle Sleeveless Shift Dress Flowy Boho Dress",
        product_price: "$39.99",
        product_original_price: "$59.99",
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 2686,
        product_url: "https://www.amazon.com/dp/B09TNHSMLT",
        product_photo:
          "https://m.media-amazon.com/images/I/71KMkjBzUWL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$39.99",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BXY3WR7D",
        product_title:
          "Ladies Cotton Linen Solid Color Fashion Casual Dress Hawaiian Beach Dress Linen V Neck Dress Summer Vacation Dress",
        product_price: "$2.32",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BXY3WR7D",
        product_photo:
          "https://m.media-amazon.com/images/I/51oo4ZFc+zL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$2.32",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B08JDYRP3Z",
        product_title: "Women's Fluid Twill Tiered Midi Summer Dress",
        product_price: "$35.80",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "3.9",
        product_num_ratings: 1702,
        product_url: "https://www.amazon.com/dp/B08JDYRP3Z",
        product_photo:
          "https://m.media-amazon.com/images/I/91pUcviQ9IL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$35.80",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B07J677DQF",
        product_title:
          "Women's Supersoft Terry Racerback Maxi Dress (Previously Daily Ritual)",
        product_price: "$27.92",
        product_original_price: "$34.90",
        currency: "USD",
        product_star_rating: "4.1",
        product_num_ratings: 1071,
        product_url: "https://www.amazon.com/dp/B07J677DQF",
        product_photo:
          "https://m.media-amazon.com/images/I/818lZwQePxL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$27.92",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B082ZT4X12",
        product_title: "Women's Long-Sleeve Banded Collar Shirt Dress",
        product_price: "$29.40",
        product_original_price: "$30.90",
        currency: "USD",
        product_star_rating: "3.9",
        product_num_ratings: 892,
        product_url: "https://www.amazon.com/dp/B082ZT4X12",
        product_photo:
          "https://m.media-amazon.com/images/I/71Fc84goeWL._AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$29.40",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BZBY7KD1",
        product_title:
          "Oversized Maxi Dress Plus Size Half Sleeve Summer Dress for Women Linen Shift Dress Solid Color Casual Dress 2023",
        product_price: "$13.15",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BZBY7KD1",
        product_photo:
          "https://m.media-amazon.com/images/I/51RyWdDt5nL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$13.15",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BXY363GN",
        product_title:
          "Women's Linen Dresses Square Neck Plain Linen Dress Vintage Casual Linen Dress Trendy Vacation Dress Summer Fashion",
        product_price: "$10.35",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BXY363GN",
        product_photo:
          "https://m.media-amazon.com/images/I/616Mj7XHanL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$10.35",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B07PN9XJQW",
        product_title:
          "Women 2023 Summer Spaghetti Strap Button Down V Neck Sleeveless Casual Mini Dress Strappy Swing A Line Shot Dresses",
        product_price: "$30.39",
        product_original_price: "$35.99",
        currency: "USD",
        product_star_rating: "4",
        product_num_ratings: 19058,
        product_url: "https://www.amazon.com/dp/B07PN9XJQW",
        product_photo:
          "https://m.media-amazon.com/images/I/61XmtWJTk9L._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$30.39",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BY1NCVFH",
        product_title:
          "Trendy 3/4 Sleeve Linen Dresses for Women Casual Summer Belted Linen Maxi Dress High Waisted Maxi Dress Fashion 2023",
        product_price: "$16.29",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BY1NCVFH",
        product_photo:
          "https://m.media-amazon.com/images/I/61F0g5TDKtL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$16.29",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BYRLM8RM",
        product_title:
          "Womens Ruched Bodycon T Shirt Dress, Empire Waist Dress with Pockets Bodycon Tank Top Midi Skirt 2 Piece Dress Temperament",
        product_price: "$7.04",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BYRLM8RM",
        product_photo:
          "https://m.media-amazon.com/images/I/61QDZyB3JoL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$7.04",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BZDT3F3L",
        product_title:
          "Women's 2023 Summer Beach Dresses, Women's Casual Loose Summer Long Dress Hide Belly Loose Fit Summer Sundress with Pockets",
        product_price: "$4.72",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BZDT3F3L",
        product_photo:
          "https://m.media-amazon.com/images/I/61SBgg3UDFL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$4.72",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BXY1TH3R",
        product_title:
          "Oversized Linen Shirt Dress for Women Linen Shift Dress Button Down Collared Shirt Dress Dressy Casual Summer Dress",
        product_price: "$13.91",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BXY1TH3R",
        product_photo:
          "https://m.media-amazon.com/images/I/51e8KOENztL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$13.91",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BXY4PSCF",
        product_title:
          "Oversized Linen Shirt Dress for Women Button Down Summer Dress Linen Maxi Dress with Pockets Trendy Casual Dress",
        product_price: "$9.21",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BXY4PSCF",
        product_photo:
          "https://m.media-amazon.com/images/I/51f2eMRiNCL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$9.21",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BXY4CMX7",
        product_title:
          "Sleeveless Linen Dress for Women Summer Boho Floral Print Maxi Dress Cheongsam Dress Flowy Hawaiian Beach Dress 2023",
        product_price: "$17.10",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BXY4CMX7",
        product_photo:
          "https://m.media-amazon.com/images/I/71jyHeEVUtL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$17.10",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B09ZHPM5PD",
        product_title:
          "Women Summer Solid Cotton Linen Dresses Casual Short Sleeve Loose Empire Waist Midi Dress Plus Size Mini Tunic Dress",
        product_price: "$17.99",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B09ZHPM5PD",
        product_photo:
          "https://m.media-amazon.com/images/I/71JYG6O11gL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$17.99",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BXY9BH63",
        product_title:
          "Women Vintage Half Sleeve Linen Plain Dresses Linen Shift Dress Casual Linen Dress with Pockets Trendy Summer Dress",
        product_price: "$10.33",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BXY9BH63",
        product_photo:
          "https://m.media-amazon.com/images/I/51p0OkljC1L._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$10.33",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BXYCXZLV",
        product_title:
          "3/4 Sleeve Linen Dresses for Women Casual Summer Trendy Summer Dresses 2023 Fashion Vacation Dress Linen Beach Dress",
        product_price: "$18.11",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BXYCXZLV",
        product_photo:
          "https://m.media-amazon.com/images/I/61xFJlUasLL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$18.11",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BXXXJTLF",
        product_title:
          "Linen Shift Dress for Women Summer Swing A Line Dress with Pockets Short Sleeve Tiered Dress Flowy Beach Dress 2023",
        product_price: "$9.80",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BXXXJTLF",
        product_photo:
          "https://m.media-amazon.com/images/I/61iLYyi8f5L._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$9.80",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B07DLDDNWK",
        product_title:
          "Women's Jersey Oversized-Fit Short-Sleeve Pocket T-Shirt Dress (Previously Daily Ritual)",
        product_price: "$23.70",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.3",
        product_num_ratings: 3663,
        product_url: "https://www.amazon.com/dp/B07DLDDNWK",
        product_photo:
          "https://m.media-amazon.com/images/I/715p15qmSpL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$23.70",
        is_best_seller: false,
        is_prime: true,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BXY5L5CB",
        product_title:
          "Women's Linen Dresses Square Neck Plain Linen Dress Vintage Casual Linen Dress Trendy Vacation Dress Summer 2023",
        product_price: "$13.54",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BXY5L5CB",
        product_photo:
          "https://m.media-amazon.com/images/I/61DLgc-97bL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$13.54",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BXY7LX4N",
        product_title:
          "Womens Plus Size Linen Maxi Dresses Linen Dress with Pockets Casual Summer Dress Long Flowy Beach Vacation Dress",
        product_price: "$11.41",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BXY7LX4N",
        product_photo:
          "https://m.media-amazon.com/images/I/51gxJr3xorL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$11.41",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BY1NGWG4",
        product_title:
          "Plus Size Linen Dress for Women Loose Fit Cotton Linen Pocket Dress Linen Crew Neck Dress Breathable Summer Dress",
        product_price: "$10.50",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BY1NGWG4",
        product_photo:
          "https://m.media-amazon.com/images/I/51gy4xOQp1L._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$10.50",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BXYJ19W6",
        product_title:
          "3/4 Sleeve Linen Dress for Women Casual Summer Dress Drawstring Waist Maxi Dress Long Linen Dress Flowy Beach Dress",
        product_price: "$10.75",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BXYJ19W6",
        product_photo:
          "https://m.media-amazon.com/images/I/61xAif+QyiL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$10.75",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
      {
        asin: "B0BXYF6NV4",
        product_title:
          "Womens Plus Size Linen Maxi Dresses Cotton Linen Pocket Dress Casual Summer Dress Long Flowy Beach Vacation Dress",
        product_price: "$12.64",
        product_original_price: null,
        currency: "USD",
        product_star_rating: null,
        product_num_ratings: 0,
        product_url: "https://www.amazon.com/dp/B0BXYF6NV4",
        product_photo:
          "https://m.media-amazon.com/images/I/61tTVfvGYvL._MCnd_AC_UL960_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: "$12.64",
        is_best_seller: false,
        is_prime: false,
        climate_pledge_friendly: false,
      },
    ],
  },
} as const;
